# Generated by Django 2.0.2 on 2018-02-25 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20180224_2025'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='pics/none.jpg', upload_to=''),
        ),
    ]
